name: HGOSpawnManager
main: org.hurricanegames.spawnmanager.SpawnManagerPlugin
api-version: 1.16
version: 1.0
authors:
- _Shevchik_
softdepend:
- SpawnAPI
commands:
  spawn:
    description: Teleport to spawn
    usage: '/<command>'
  fspawn:
    description: Force teleport other player to spawn
    usage: '/<command> {player}'
  setspawn:
    description: Set spawn location
    usage: '/<command>'
