name: HGOSpawnManager
main: org.hurricanegames.spawnmanager.SpawnManagerPlugin
api-version: 1.16
version: 1.3

softdepend:
- SpawnAPI

commands:
  spawnmanageradmin:
    description: SpawnManager admin commands
    usage: '/<command>'
  spawn:
    description: Teleport to spawn
    usage: '/<command>'
  fspawn:
    description: Force teleport other player to spawn
    usage: '/<command> {player}'
  setspawn:
    description: Set spawn location
    usage: '/<command>'

permissions:
  hgo.spawnmanager.admin:
    description: Admin access
    default: op
  hgo.spawnmanager.teleport.nodelay:
    description: Teleport to spawn without delay
    default: op

authors:
- _Shevchik_
website: 'https://github.com/HurricaneGamesOrg/HurricaneGamesOrgSpawnManager'
